spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/template_dev}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.demo: DEBUG

app:
  logging:
    http:
      enabled: true
